-- Align persisted system definitions with the canonical permission catalogue.
-- Custom role IDs and role assignments are preserved.
--> statement-breakpoint
UPDATE roles SET permissions_json = '["organization.delete","organization.transfer","organization.get","organization.update","workspaces.get","workspaces.create","workspaces.update","members.manage","teams.manage","roles.manage","workspaces.curate","workspaces.delete","workspaces.transfer","providers.manage","providers.viewMetadata","providers.create","providers.update","providers.delete","providers.test","models.manage","models.view","models.invoke","models.create","models.update","models.delete","models.sync","agents.manage","agents.list","agents.get","agents.chat","agents.create","agents.update","agents.delete","agents.test","agents.delegate","agentVersions.manage","agentVersions.create","tools.manage","tools.view","tools.configure","tools.executeRestricted","mcpServers.manage","mcpServers.get","knowledgeBases.manage","knowledgeBases.viewAllowed","conversations.manage","conversations.create","conversations.viewOwn","usage.view","audit.view","audit.export","marketplaceItems.view","marketplaceItems.install","marketplaceItems.publish","apiKeys.manage","workflows.view","workflows.create","workflows.update","workflows.delete","workflows.execute"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'organization.owner' AND scope_type = 'organization';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["workspaces.curate","workspaces.delete","workspaces.transfer","workspaces.get","workspaces.update","roles.manage","providers.manage","providers.viewMetadata","providers.create","providers.update","providers.delete","providers.test","models.manage","models.view","models.invoke","models.create","models.update","models.delete","models.sync","agents.manage","agents.list","agents.get","agents.chat","agents.create","agents.update","agents.delete","agents.test","agents.delegate","agentVersions.manage","agentVersions.create","tools.manage","tools.view","tools.configure","tools.executeRestricted","mcpServers.manage","mcpServers.get","knowledgeBases.manage","knowledgeBases.viewAllowed","conversations.manage","conversations.create","conversations.viewOwn","usage.view","audit.view","audit.export","marketplaceItems.view","marketplaceItems.install","marketplaceItems.publish","apiKeys.manage","workflows.view","workflows.create","workflows.update","workflows.delete","workflows.execute","organization.get","organization.update","workspaces.get","workspaces.create","workspaces.update","members.manage","teams.manage","roles.manage","audit.view"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'organization.admin' AND scope_type = 'organization';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["organization.get"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'organization.user' AND scope_type = 'organization';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["workspaces.curate","workspaces.delete","workspaces.transfer","workspaces.get","workspaces.update","roles.manage","providers.manage","providers.viewMetadata","providers.create","providers.update","providers.delete","providers.test","models.manage","models.view","models.invoke","models.create","models.update","models.delete","models.sync","agents.manage","agents.list","agents.get","agents.chat","agents.create","agents.update","agents.delete","agents.test","agents.delegate","agentVersions.manage","agentVersions.create","tools.manage","tools.view","tools.configure","tools.executeRestricted","mcpServers.manage","mcpServers.get","knowledgeBases.manage","knowledgeBases.viewAllowed","conversations.manage","conversations.create","conversations.viewOwn","usage.view","audit.view","audit.export","marketplaceItems.view","marketplaceItems.install","marketplaceItems.publish","apiKeys.manage","workflows.view","workflows.create","workflows.update","workflows.delete","workflows.execute"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'workspace.admin' AND scope_type = 'workspace';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["workspaces.get","providers.viewMetadata","models.view","models.invoke","agents.list","agents.get","agents.chat","agents.create","agents.update","agents.delete","agents.test","agents.delegate","agentVersions.create","tools.view","tools.configure","tools.executeRestricted","mcpServers.get","mcpServers.manage","knowledgeBases.viewAllowed","knowledgeBases.manage","conversations.create","conversations.viewOwn","marketplaceItems.view","marketplaceItems.install","marketplaceItems.publish","apiKeys.manageOwn","workflows.view","workflows.create","workflows.update","workflows.delete","workflows.execute"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'workspace.member' AND scope_type = 'workspace';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["workspaces.get","providers.viewMetadata","models.view","agents.list","agents.get","tools.view","mcpServers.get","knowledgeBases.viewAllowed","marketplaceItems.view","usage.view","audit.view","workflows.view"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'workspace.viewer' AND scope_type = 'workspace';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["knowledgeBases.viewAllowed","knowledgeBases.manage"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'workspace.knowledge_editor' AND scope_type = 'workspace';
--> statement-breakpoint
UPDATE roles SET permissions_json = '["agents.get","agents.chat","agents.test"]'::jsonb, updated_at = now() WHERE is_system = true AND name = 'workspace.agent_user' AND scope_type = 'workspace';
--> statement-breakpoint
-- Materialize historical wildcard and view/manage aggregates for inspectable roles.
WITH catalogue AS (SELECT jsonb_array_elements_text('["workspaces.curate","organization.delete","organization.transfer","workspaces.delete","workspaces.transfer","roles.get","roles.create","roles.update","roles.delete","roles.assign","roles.revoke","members.create","members.delete","teams.create","teams.update","teams.delete","organization.get","organization.update","workspaces.get","workspaces.create","workspaces.update","members.manage","teams.manage","roles.manage","agents.test","agents.manage","agents.list","agents.get","agents.chat","agents.create","agents.update","agents.delete","agents.delegate","agentVersions.create","agentVersions.manage","conversations.create","conversations.viewOwn","conversations.manage","providers.create","providers.update","providers.delete","providers.test","models.create","models.update","models.delete","models.sync","tools.manage","providers.viewMetadata","providers.manage","models.view","models.invoke","models.manage","tools.view","tools.configure","tools.executeRestricted","mcpServers.get","mcpServers.manage","knowledgeBases.viewAllowed","knowledgeBases.manage","workflows.view","workflows.create","workflows.update","workflows.execute","workflows.delete","usage.view","audit.view","audit.export","marketplaceItems.view","marketplaceItems.install","marketplaceItems.publish","apiKeys.manageOwn","apiKeys.manage"]'::jsonb) AS permission), expanded AS (
 SELECT r.id, jsonb_agg(DISTINCT c.permission) AS permissions
 FROM roles r CROSS JOIN LATERAL jsonb_array_elements_text(r.permissions_json) grant_entry(value)
 JOIN catalogue c ON c.permission = grant_entry.value
 OR grant_entry.value = '*'
 OR (array_length(string_to_array(grant_entry.value, '.'), 1) = 2 AND split_part(c.permission, '.', 1) = split_part(grant_entry.value, '.', 1)
 AND (split_part(grant_entry.value, '.', 2) IN ('*', 'manage')
 OR (split_part(grant_entry.value, '.', 2) = 'view' AND split_part(c.permission, '.', 2) IN ('get', 'list', 'view', 'viewAllowed', 'viewMetadata', 'viewOwn'))))
 WHERE r.is_system = false AND jsonb_typeof(r.permissions_json) = 'array'
 GROUP BY r.id
) UPDATE roles SET permissions_json = expanded.permissions, updated_at = now() FROM expanded WHERE roles.id = expanded.id;
